// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9USatXwemOgDTD38JjI_XhBuI4iUjegQ',
    appId: '1:1054463304738:web:fdbf08d82c7d45e884567b',
    messagingSenderId: '1054463304738',
    projectId: 'cardtrick-acea0',
    authDomain: 'cardtrick-acea0.firebaseapp.com',
    storageBucket: 'cardtrick-acea0.appspot.com',
    measurementId: 'G-Y47Y60RKWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2s6RSKlM_YXTBAgxppxUCt_OYmtTKUB4',
    appId: '1:1054463304738:android:7c53b61e04dc5ab684567b',
    messagingSenderId: '1054463304738',
    projectId: 'cardtrick-acea0',
    storageBucket: 'cardtrick-acea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7uVWdcC9WoZ1eIZMQZ4W17x8WsSCQ4M',
    appId: '1:1054463304738:ios:290f75c6eecb005f84567b',
    messagingSenderId: '1054463304738',
    projectId: 'cardtrick-acea0',
    storageBucket: 'cardtrick-acea0.appspot.com',
    iosBundleId: 'gr.techzombie.cardtrick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM7uVWdcC9WoZ1eIZMQZ4W17x8WsSCQ4M',
    appId: '1:1054463304738:ios:ea4a82434dafbc3f84567b',
    messagingSenderId: '1054463304738',
    projectId: 'cardtrick-acea0',
    storageBucket: 'cardtrick-acea0.appspot.com',
    iosBundleId: 'gr.techzombie.cardtrick.RunnerTests',
  );
}
